kafka:
  bootstrapServers:
    - 127.0.0.1:9092
  topic: events
  numPartitions: 3
  replicationFactor: 1
  retention: "-1"
  consumerGroup: CommonProjection
  producer:
    retryMax: 10
    returnSuccess: true
    retryBackoff: 2s
    clientId: "chat-producer"
  consumer:
    returnErrors: true
    clientId: "chat-consumer"
    nackResendSleep: 100ms
    reconnectRetrySleep: 1s
otlp:
  endpoint: localhost:4317
postgresql:
  url: "postgres://postgres:postgresqlPassword@localhost:5432/postgres?sslmode=disable&application_name=cqrs-app"
  maxOpenConnections: 16
  maxIdleConnections: 4
  maxLifetime: 30s
server:
  address: ":8080"
  readTimeout: "10s"
  writeTimeout: "10s"
  maxHeaderBytes: 20000000
